INSERT INTO MOVETYPE (ID, NAME, MINUTES) VALUES (1, 'Laufen R-R', 120);
INSERT INTO MOVETYPE (ID, NAME, MINUTES) VALUES (2, 'Radfahren R-R', 45);
INSERT INTO MOVETYPE (ID, NAME, MINUTES) VALUES (3, 'Laufen Mittag', 45);
INSERT INTO MOVETYPE (ID, NAME, MINUTES) VALUES (4, 'Auto R-R', 0);

DELETE FROM ONEDAY;

select * from APPONE.ONEDAY;